version: '2'
services:
  mysql:
    container_name: dev-db
    build: ./mysql
    volumes_from:
      - data
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: test
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - ./init.d:/docker-entrypoint-initdb.d

  php:
    container_name: dev-php
    build: ./web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/var/www/html
    depends_on:
      - mysql

  data:
    container_name: dev-data
    image: busybox
    volumes:
      - /var/lib/mysql
